# Generated by Django 4.2.30 on 2026-06-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('client_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('progress', models.IntegerField()),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
