# Generated by Django 4.2.30 on 2026-06-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('client_name', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('delivery_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
