# Generated by Django 4.2.30 on 2026-06-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_portfolio_description_portfolio_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
