# Generated by Django 4.2.30 on 2026-06-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_file',
            field=models.FileField(blank=True, null=True, upload_to='deliveries/'),
        ),
    ]
