# Generated by Django 4.2.30 on 2026-06-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_customer_email_order_momo_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='momo_reference',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
